# Erik Santana Montelongo
# **Responder a las siguientes preguntas:**


1.   Calcular la media y la mediana antes de realizar la modificación de incluir unos ingresos de 500.000€

2.   Aplicar el método de Probabilidad global, para detectar los outliers utilizado en el ejemplo 2_3_Outliers (Url:https://colab.research.google.com/drive/1C6uBUxui_Qq9ee-51ycVYcqigrSHSZNY?usp=sharing)

3.   Repetir el mismo procedimiento de detectar los outliers para la
mediana: ¿Qué ocurre?


# a) Calcular la media y la mediana antes de realizar la modificación de incluir unos ingresos de 500.000€

In [15]:
import numpy as np
import pandas as pd
import scipy.stats as st

datos = 15000+np.random.rand(100)*10000
datos_ord = datos
datos_ord.sort()
datos

array([15022.80430473, 15045.03147163, 15282.07448288, 15287.12202144,
       15346.38261049, 15438.99849886, 15447.85048388, 15776.37782915,
       16020.69753649, 16068.45235812, 16188.4276136 , 16486.59853492,
       16504.62832241, 16612.4118564 , 16665.79721776, 16908.6867429 ,
       16913.71458515, 17034.70862748, 17269.39632234, 17308.87669954,
       17320.58931122, 17481.64785924, 17528.80610788, 17602.82710768,
       17606.82148083, 17615.35357556, 17623.80442856, 17667.73823853,
       17731.8432514 , 17756.93013556, 17805.74719794, 17807.53463811,
       17829.81318523, 17907.50089394, 17961.88852936, 17968.18216249,
       18341.02788082, 18378.68604841, 18398.91436417, 18526.45371714,
       18549.3912295 , 18747.50147921, 18797.32283422, 18914.06641021,
       18971.97998908, 19086.28582227, 19102.06172153, 19260.20349131,
       19384.68881141, 19445.57450865, 19902.57629539, 20032.7333098 ,
       20097.74370107, 20205.33235925, 20300.98122207, 20332.37862153,
      

In [8]:
media=  np.mean(datos)
mediana=  np.median (datos)
print(f" Media= {media} y Mediana={mediana}")

 Media= 20084.98898016097 y Mediana=20406.482194406366


# b) Aplicar el método de Probabilidad global, para detectar los outliers

In [18]:
# Cambiamos los valores de dos datos para convertirlos en outliers
datos[50]=500000
datos

array([ 15022.80430473,  15045.03147163,  15282.07448288,  15287.12202144,
        15346.38261049,  15438.99849886,  15447.85048388,  15776.37782915,
        16020.69753649,  16068.45235812,  16188.4276136 ,  16486.59853492,
        16504.62832241,  16612.4118564 ,  16665.79721776,  16908.6867429 ,
        16913.71458515,  17034.70862748,  17269.39632234,  17308.87669954,
        17320.58931122,  17481.64785924,  17528.80610788,  17602.82710768,
        17606.82148083,  17615.35357556,  17623.80442856,  17667.73823853,
        17731.8432514 ,  17756.93013556,  17805.74719794,  17807.53463811,
        17829.81318523,  17907.50089394,  17961.88852936,  17968.18216249,
        18341.02788082,  18378.68604841,  18398.91436417,  18526.45371714,
        18549.3912295 ,  18747.50147921,  18797.32283422,  18914.06641021,
        18971.97998908,  19086.28582227,  19102.06172153,  19260.20349131,
        19384.68881141,  19445.57450865, 500000.        ,  20032.7333098 ,
        20097.74370107,  

In [19]:
p_g=0.95
alfa_g=(1-p_g)/2
alfa= 1-(1-alfa_g)**(1/len(datos))

In [20]:
Z_alfa=st.norm.ppf(1-alfa/2)

In [21]:
# Impresión de resultados
alfa=round(alfa,5)
Z_alfa=round(Z_alfa,5)
print(f" Alfa ={alfa}")
print(f" Z_alfa ={Z_alfa}")

 Alfa =0.00025
 Z_alfa =3.65906


In [22]:
# Utilizaremos el Criterio 1 ó el Criuterio 2 para calcular alfa y Z-alfa en función de la naturaleza de los datos que estamos procesando.
xL=  round(np.mean(datos)-Z_alfa*  np.std(datos),4)
xU=  round(np.mean(datos)+Z_alfa*  np.std(datos),4)
print(f" Banda= [ {xL},{xU}]")

 Banda= [ -150371.7404,199827.7618]


In [23]:
for i in  range(len(datos)):
        if datos[i] < xL  or datos[i]>xU:
          print(f" El dato[{i}]={datos[i]} es un outlier")

 El dato[50]=500000.0 es un outlier


# c) Repetir el mismo procedimiento de detectar los outliers para la mediana: ¿Qué ocurre?

In [24]:
import numpy as np
import pandas as pd

datos_ord = datos
datos_ord.sort()
datos

array([ 15022.80430473,  15045.03147163,  15282.07448288,  15287.12202144,
        15346.38261049,  15438.99849886,  15447.85048388,  15776.37782915,
        16020.69753649,  16068.45235812,  16188.4276136 ,  16486.59853492,
        16504.62832241,  16612.4118564 ,  16665.79721776,  16908.6867429 ,
        16913.71458515,  17034.70862748,  17269.39632234,  17308.87669954,
        17320.58931122,  17481.64785924,  17528.80610788,  17602.82710768,
        17606.82148083,  17615.35357556,  17623.80442856,  17667.73823853,
        17731.8432514 ,  17756.93013556,  17805.74719794,  17807.53463811,
        17829.81318523,  17907.50089394,  17961.88852936,  17968.18216249,
        18341.02788082,  18378.68604841,  18398.91436417,  18526.45371714,
        18549.3912295 ,  18747.50147921,  18797.32283422,  18914.06641021,
        18971.97998908,  19086.28582227,  19102.06172153,  19260.20349131,
        19384.68881141,  19445.57450865,  20032.7333098 ,  20097.74370107,
        20205.33235925,  

In [25]:
media=  np.mean(datos)
mediana=  np.median (datos)
print(f" Media= {media} y Mediana={mediana}")

 Media= 24728.01070236752 y Mediana=19739.153909224446


In [26]:
phi=np.zeros(len(datos))
for i in  range(len(datos)):
  datos_aux=datos
  datos_sin_i=np.delete(datos_aux, i)
  phi[i]=np.median(datos_sin_i)
phi

array([20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 20032.7333098 , 20032.7333098 ,
       20032.7333098 , 20032.7333098 , 19445.57450865, 19445.57450865,
       19445.57450865, 19445.57450865, 19445.57450865, 19445.57450865,
      

In [27]:
# Aplicamos el método de la distancia entre cuartiles, en este caso, al aplicar el método Jackknife no obtenemos
# el valor del elemento que es considerado Outlier, sino la posición del mismo.
Q1 = np.quantile(phi,0.25)
Q3 = np.quantile(phi,0.75)
IQR = Q3 - Q1
xL=Q1 - 1.5 * IQR
xU=Q3 + 1.5 * IQR
for i in  range(len(datos)):
        if phi[i] < xL  or phi[i]>xU:
          print(f" El dato {i} es una observación influyente para la mediana")

In [28]:
pd.DataFrame(phi).describe()

0
count    100.000000
mean   19739.153909
std      295.058399
min    19445.574509
25%    19445.574509
50%    19739.153909
75%    20032.733310
max    20032.733310

# Considerar que la variable X toma los valores 1,2,3,4,5,6,7,8,9,10

# a) ¿Cuánto vale la media, mediana, la desviación estándar muestral, la varianza muestral y el rango de la variable X?

In [1]:
import numpy as np

# Definir la variable X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calcular estadísticas
media = np.mean(X)  # Media
mediana = np.median(X)  # Mediana
desviacion_std_muestral = np.std(X, ddof=1)  # Desviación estándar muestral
varianza_muestral = np.var(X, ddof=1)  # Varianza muestral
rango = np.ptp(X)  # Rango

print("Media:", media)
print("Mediana:", mediana)
print("Desviacion estándar muestral:", desviacion_std_muestral)
print("Varianza muestral:", varianza_muestral)
print("Rango:", rango)

Media: 5.5
Mediana: 5.5
Desviación estándar muestral: 3.0276503540974917
Varianza muestral: 9.166666666666666
Rango: 9


# b) Utilizar la función describe() de Panda, para obtener la media, desviación estándar, etc…


In [2]:
import pandas as pd

data = pd.DataFrame({'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
estadisticas_descriptivas = data.describe()
print(estadisticas_descriptivas)

              X
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000


# c) ¿Por qué el resultado de calcular la desviación estándar con Numpy es diferente a la calculada por describe de Panda? ¿Qué ajuste sería necesario realizar para que los resultados fuesen similares/iguales?

La diferencia ocurre porque:

*   Numpy (std por defecto) calcula la desviación estándar poblacional (𝑁 en el denominador).
*   Pandas (describe) usa la desviación estándar muestral (𝑁 − 1 en el denominador).



In [3]:
import numpy as np
import pandas as pd

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Desviación con numpy (por defecto: poblacional)
desviacion_std_numpy_poblacional = np.std(X)

# Desviación con numpy (ajustada: muestral)
desviacion_std_numpy_muestral = np.std(X, ddof=1)

# Desviación con pandas
data = pd.DataFrame({'X': X})
desviacion_std_pandas = data['X'].std()

print("Desviación estándar (Numpy, poblacional):", desviacion_std_numpy_poblacional)
print("Desviación estándar (Numpy, muestral):", desviacion_std_numpy_muestral)
print("Desviación estándar (Pandas, describe):", desviacion_std_pandas)

Desviación estándar (Numpy, poblacional): 2.8722813232690143
Desviación estándar (Numpy, muestral): 3.0276503540974917
Desviación estándar (Pandas, describe): 3.0276503540974917


# d) Estandarizar la variable (escalamiento) mediante rangos y a continuación calcular la media y la mediana de la variable escalada

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Escalamiento mediante rangos
scaler = MinMaxScaler()
X_escalado = scaler.fit_transform(X.reshape(-1, 1)).flatten()

# Calcular la media y mediana de la variable escalada
media_escalada = np.mean(X_escalado)
mediana_escalada = np.median(X_escalado)

print("Variable escalada:", X_escalado)
print("Media de la variable escalada:", media_escalada)
print("Mediana de la variable escalada:", mediana_escalada)

Variable escalada: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Media de la variable escalada: 0.5
Mediana de la variable escalada: 0.5


# e) Repetir el apartado anterior con el escalamiento Z - score

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Escalamiento Z-Score
scaler_z = StandardScaler()
X_escalado_z = scaler_z.fit_transform(X.reshape(-1, 1)).flatten()

# Calcular la media y mediana de la variable escalada con Z-score
media_escalada_z = np.mean(X_escalado_z)
mediana_escalada_z = np.median(X_escalado_z)

print("Variable escalada (Z-Score):", X_escalado_z)
print("Media de la variable escalada (Z-Score):", media_escalada_z)
print("Mediana de la variable escalada (Z-Score):", mediana_escalada_z)


Variable escalada (Z-Score): [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
Media de la variable escalada (Z-Score): -6.661338147750939e-17
Mediana de la variable escalada (Z-Score): 0.0
